services:
  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb-leadsoft
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - ravendb_data:/opt/RavenDB/Server/RavenData
volumes:
  ravendb_data: